<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The Building Coder</title>
    <link rel="stylesheet" href="bc.css">
    <link rel="stylesheet" href="google-code-prettify/prettify.css">
    <script src="google-code-prettify/run_prettify.js"></script>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        a { color: #0066cc; }
        img { max-width: 100%; height: auto; }
        .nav { margin-bottom: 20px; padding: 10px; background: #f5f5f5; border-radius: 5px; }
        .nav a { margin-right: 15px; }
    </style>
</head>
<body>
    <div class="nav">
        <a href="index.html">← Back to Index</a>
    </div>
    <article>
<p><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="bc.css">
<!--
<script src="run_prettify.js" type="text/javascript"></script>
<script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js" type="text/javascript"></script>
-->
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js" type="text/javascript"></script>
</head></p>
<!---

- 13540959 [GetAnalyticalModelSupports how to use this]
  https://forums.autodesk.com/t5/revit-api-forum/getanalyticalmodelsupports-how-to-use-this/m-p/7503547
  /a/doc/revit/tbc/git/a/1608_analyticalmodelsupport.md

 #RevitAPI @AutodeskRevit #bim #dynamobim @AutodeskForge #ForgeDevCon

I'm trying to retrieve connected framing elements through the API.
My end goal is to select a beam and retrieve the element id of the elements its ends are framing into.
I have been able to do this by checking location intersection of all other beams, but this scales by <code>n^2</code> based on the number of beams for the check.
I read the article on finding connected structural elements, but I'm confused on the actual implementation of it.
Has anybody come across a working example showing how to
call <code>GetAnalyticalModelSupports</code>? ...

--->

<h3>How to Use GetAnalyticalModelSupports</h3>
<p>I highlight yet another thread from 
the <a href="http://forums.autodesk.com/t5/revit-api-forum/bd-p/160">Revit API discussion forum</a>,
on <a href="https://forums.autodesk.com/t5/revit-api-forum/getanalyticalmodelsupports-how-to-use-this/m-p/7503547">how to use GetAnalyticalModelSupports</a>,
answered by Dragos Turmac, Autodesk Software Engineer, and with additional usage hints by J. Peele, who also raised the question in the first place:</p>
<p><strong>Question:</strong> I'm trying to retrieve connected framing elements through the API.</p>
<p>My end goal is to select a beam and retrieve the element id of the elements its ends are framing into.</p>
<p>I have been able to do this by checking location intersection of all other beams, but this scales by <code>n^2</code> based on the number of beams for the check.</p>
<p>I read the article 
on <a href="0508_connected_rst_elements.htm">finding connected structural elements</a>, 
but I'm confused on the actual implementation of it.</p>
<p>Has anybody come across a working example showing how to
call <a href="http://www.revitapidocs.com/2018.1/15f01976-9e34-8850-6fa8-79c77a7ed3a4.htm"><code>GetAnalyticalModelSupports</code></a>?</p>
<p>I'm not sure what objects have this property since they all seem to inherit it. Or am I missing an import?</p>
<p>I'm working in Python. Here is the code so far:</p>
<pre class="prettyprint">
  import clr
  clr.AddReference('ProtoGeometry')
  from Autodesk.DesignScript.Geometry import *

  # Import RevitAPI
  clr.AddReference('RevitAPI')
  import Autodesk
  from Autodesk.Revit.DB import *

  # Import ToDSType(bool) extension method
  clr.AddReference('RevitNodes')
  import Revit
  clr.ImportExtensions(Revit.Elements)

  from Autodesk.Revit.DB.Structure import *

  # The inputs to this node will be stored as a list in the IN variables.
  dataEnteringNode = IN

  if isinstance(IN[0], list):
    elements = [UnwrapElement(i) for i in IN[0]]
  else:
    elements = [UnwrapElement(IN[0])]

  AnalyticalEl = [element.GetAnalyticalModel() for element in elements]

  # Assign your output to the OUT variable.
  OUT = AnalyticalEl;
</pre>

<p>Thanks so much for any help you can give.</p>
<p><strong>Answer:</strong> Does this snippet work for you and answer your question?</p>
<pre class="code">
&nbsp;&nbsp;<span style="color:#2b91af;">AnalyticalModel</span>&nbsp;model
&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;aWallFoundation.GetAnalyticalModel()&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">as</span>&nbsp;<span style="color:#2b91af;">AnalyticalModel</span>;

&nbsp;&nbsp;<span style="color:blue;">if</span>(&nbsp;<span style="color:blue;">null</span>&nbsp;==&nbsp;model&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:blue;">continue</span>;

&nbsp;&nbsp;<span style="color:#2b91af;">IList</span>&lt;<span style="color:#2b91af;">AnalyticalModelSupport</span>&gt;&nbsp;supports&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;model.GetAnalyticalModelSupports();

&nbsp;&nbsp;<span style="color:#2b91af;">List</span>&lt;<span style="color:#2b91af;">ElementId</span>&gt;&nbsp;ids&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;=&nbsp;<span style="color:blue;">new</span>&nbsp;<span style="color:#2b91af;">List</span>&lt;<span style="color:#2b91af;">ElementId</span>&gt;();

&nbsp;&nbsp;<span style="color:blue;">foreach</span>(&nbsp;<span style="color:#2b91af;">AnalyticalModelSupport</span>&nbsp;m&nbsp;<span style="color:blue;">in</span>&nbsp;supports&nbsp;)
&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;ids.Add(&nbsp;m.GetSupportingElement()&nbsp;);
&nbsp;&nbsp;}
</pre>

<p><strong>Response:</strong> Finally got it working yesterday.</p>
<p>This code does the trick, though the problem was a conceptual oversight on my part.</p>
<p>I was imagining the supports would be similar to what pressing tab on a beam element does; however, it seems the supports are actually the members involved in the gravity load path.</p>
<p>More importantly, the analytical supports will be null if Revit has 'Automatic Member Supports' turned off (as it should be, Revit is unusably slow on large projects with it on).</p>
<p>I had to run a manual support check before anything would show up.</p>
<p>Hope this helps anyone having similar issue to what I ran into. Also, if there is any way to programmatically get the connected beams similar to how tab behaviour works, I would still be interested to learn how.</p>
<p>Many thanks to Dragos and J. for raising and solving this issue!</p>
<p><center>
<img src="img/rst_framing_supports.png" alt="Structural framing supports" width="323"/>
</center></p>
    </article>
    <div class="nav">
        <a href="index.html">← Back to Index</a>
    </div>
</body>
</html>
